name: CI/CD for Dockerized UI Package

on:
  push:
    branches:
      - master
    paths:
      - 'packages/ui/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/ui/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cac
