name: TurboRepo CI/CD for Dockerized Apps

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-nextjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for Next.js
        run: |
          docker build -t nextjs-app ./apps/nextjs
          npx vercel container push nextjs-app vercel://${{ secrets.VERCEL_PROJECT_ID_NEXTJS }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_NEXTJS }}

      - name: Deploy Next.js app
        run: |
          npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN_NEXTJS }}

  deploy-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for UI package
        run: |
          docker build -t ui-package ./packages/ui
          npx vercel container push ui-package vercel://${{ secrets.VERCEL_PROJECT_ID_UI }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_UI }}

      - name: Deploy UI package
        run: |
          npx vercel deploy --prebuilt --token ${{ secrets.VERCEL_TOKEN_UI }}
