name: TurboRepo CI/CD for Dockerized UI Package
on:
  push:
    branches:
      - master
    paths:
      - 'packages/ui/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/ui/**'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 4: Login to Vercel
      - name: Vercel Login
        run: vercel login ${{ secrets.VERCEL_EMAIL }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_UI }}

      # Step 5: Link Vercel Project
      - name: Link Vercel Project
        working-directory: packages/ui
        run: vercel link --yes --token ${{ secrets.VERCEL_TOKEN_UI }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_UI }}

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        working-directory: packages/ui
        run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN_UI }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_UI }}
