name: TurboRepo CI/CD for Dockerized UI Package
on:
  push:
    branches:
      - master
    paths:
      - 'packages/ui/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/ui/**'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: packages/ui
        run: npm install

      # Step 4: Build Storybook
      - name: Build Storybook
        working-directory: packages/ui
        run: npm run build-storybook

      # Step 5: Deploy to Vercel
      - name: Deploy to Vercel
        working-directory: packages/ui
        run: |
          npx vercel deploy --prebuilt --prod \
            --token ${{ secrets.VERCEL_TOKEN_UI }} \
            --scope ${{ secrets.VERCEL_ORG_ID }} \
            --build-env CI=true \
            storybook-static
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_UI }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
