name: TurboRepo CI/CD for Dockerized UI Package
on:
  push:
    branches:
      - master
    paths:
      - 'packages/ui/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/ui/**'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 4: Configure Vercel
      - name: Configure Vercel
        run: |
          vercel config set projectId ${{ secrets.VERCEL_PROJECT_ID_UI }}
          vercel config set orgId ${{ secrets.VERCEL_TEAM_ID }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_UI }}

      # Step 5: Deploy to Vercel
      - name: Deploy to Vercel
        working-directory: packages/ui
        run: |
          vercel deploy --prebuilt --prod \
            --token ${{ secrets.VERCEL_TOKEN_UI }} \
            --scope ${{ secrets.VERCEL_TEAM_ID }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_UI }}
