name: TurboRepo CI/CD for Dockerized UI Package

on:
  push:
    branches:
      - master
    paths:
      - 'packages/ui/**'
  pull_request:
    branches:
      - master
    paths:
      - 'packages/ui/**'

jobs:
  deploy-ui:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Build Docker image for UI package
      - name: Build Docker Image for UI package
        run: |
          docker buildx build -t ui-package -f packages/ui/Dockerfile .

      # Step 5: Push to Vercel Container Registry
      - name: Push to Vercel Container Registry
        run: |
          npx vercel container push ui-package vercel://${{ secrets.VERCEL_PROJECT_ID_UI }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_UI }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_UI }}

      # Step 6: Deploy UI package to Vercel
      - name: Deploy UI package to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_UI }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_UI }}
        working-directory: packages/ui
        run: |
          npx vercel deploy --prod --yes
