name: Deploy Turbo Monorepo to Vercel

on:
  push:
    branches:
      - master
    paths:
      - 'apps/web/**'
      - 'packages/ui/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the Project
        run: pnpm turbo run build --filter=web

      - name: Log in to Docker Hub (Optional, if using an external registry)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image (Optional)
        run: docker build -t vaibhav143/turbowebapp:${{ github.sha }} -f apps/web/Dockerfile .

      # Remove docker push step as Vercel builds the Docker image itself
      # - name: Push Docker Image to Docker Hub (Optional)
      #   run: docker push <your_dockerhub_username>/<your_repository>:${{ github.sha }}

      - name: Deploy to Vercel
        run: |
          npx vercel deploy --token ${{ secrets.VERCEL_TOKEN_NEXTJS }} --cwd=apps/web --prod --yes
