name: Deploy Turbo Monorepo to Vercel

on:
  push:
    branches:
      - master
    # Trigger actions only when relevant files change
    paths:
      - 'apps/web/**' # Changes in the Next.js app directory
      - 'packages/ui/**' # Changes in the Storybook directory
      - '.github/workflows/**' # Changes to the GitHub Actions workflows
      - 'pnpm-lock.yaml' # Changes to lockfile or dependencies

jobs:
  deploy-nextjs:
    name: Deploy Next.js App
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.event.head_commit.message != 'skip-ci' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Turbo Repo
        run: pnpm turbo run build --filter=apps/web

      - name: Build Docker Image
        run: |
          docker build -t nextjs-app -f apps/web/Dockerfile .
          echo ${{ secrets.VERCEL_TOKEN }} | docker login --username ${{ secrets.VERCEL_ORG_ID }} --password-stdin registry.vercel.app

      - name: Push Docker Image
        run: |
          docker tag nextjs-app registry.vercel.app/${{ secrets.VERCEL_ORG_ID }}/web
          docker push registry.vercel.app/${{ secrets.VERCEL_ORG_ID }}/web

  deploy-storybook:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.event.head_commit.message != 'skip-ci' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Turbo Repo
        run: pnpm turbo run build --filter=packages/ui

      - name: Build Docker Image
        run: |
          docker build -t storybook-ui -f packages/ui/Dockerfile .
          echo ${{ secrets.VERCEL_TOKEN }} | docker login --username ${{ secrets.VERCEL_ORG_ID }} --password-stdin registry.vercel.app

      - name: Push Docker Image
        run: |
          docker tag storybook-ui registry.vercel.app/${{ secrets.VERCEL_ORG_ID }}/ui
          docker push registry.vercel.app/${{ secrets.VERCEL_ORG_ID }}/ui
